volumes:
  wg_status_to_mqtt:
    external: true
    
services:
  wg_status_to_mqtt:
    # Uncomment one of these. Use :latest if you want the stable build, use :dev if you want the development build
    image: iainbullock/wg_status_to_mqtt:latest
    #image: iainbullock/wg_status_to_mqtt:dev
    container_name: wg_status_to_mqtt
   
    volumes:
      - wg_status_to_mqtt:/config
    
    network_mode: host
    
    cap_add:
      - NET_ADMIN

    environment:
      - AP_IFACE=wlan0
      - UPLINK_IFACE=eth0
      
    # Allow opening of a shell in container
    tty: true
    stdin_open: true    
    # Uncomment if you need a container shell when the container won't run 
    # entrypoint: "/bin/ash"
    
    restart: unless-stopped
    stop_grace_period: 2m
